#!/usr/bin/env bash
#
# Description: attach /backup drive to system
#

DEVICE='/dev/xvdb'
INSTANCE=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
MTDIR='/data'
VOLUME='vol-0c4b366aad94401b7'

# check if volume already mounted
mountpoint -q $MTDIR

# mount volume if not mounted
if [[ $? -eq 0 ]]
then
    echo "$MTDIR already mounted"
        exit 0
else
        # attach volume to instance
        echo "Attaching ${MTDIR}..."
        aws ec2 attach-volume --volume-id $VOLUME --instance-id $INSTANCE --devi
ce $DEVICE &> /dev/null
        # allow time for attaching
        sleep 4
        # check attachment and mount
        if [[ ${DEVICE}1 ]]
        then
                sudo mount ${DEVICE}1 $MTDIR 2> /dev/null
        fi
fi

# check success of mount
mountpoint -q $MTDIR
if [[ $? ]]
then
        echo "Success: $MTDIR attached"
else
        echo "Error: attach failed"
fi
