#!/usr/bin/env bash
#
# Description: detach /backup drive from system
#

DEVICE=/dev/xvdf
INSTANCE=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
MTDIR=/data
VOLUME=vol-03c3049ae542aa863

# check if volume mounted
mountpoint -q $MTDIR

# unmount volume if mounted
if [[ $? -eq 0 ]]
then
        echo "Detaching ${MTDIR}..."
        sudo umount $MTDIR 2> /dev/null
        aws ec2 detach-volume --volume-id $VOLUME --instance-id $INSTANCE &> /dev/null
else
        echo "$MTDIR not mounted"
        exit 0
fi

# check success of unmounting
mountpoint -q $MTDIR
if [[ $? -eq 0 ]]
then
        echo "Error: detach failed"
else
        echo "Success: $MTDIR detached"
fi
