#!/usr/bin/env bash
# 
# edit cluster definitions using EDITOR
#
##

CONFDIR=$HOME/.cfncluster
EDITOR=/usr/bin/vim
PS3="Select number: "
TEMPLATE=$CONFDIR/spot						# default template
TEMPLATE_ONDEMAND=$CONFDIR/ondemand
TEMPLATE_SPOT=$CONFDIR/spot

usage() {
	echo "Usage: edit-cluster [-o] [-s] <filename>"
}

# Select cluster type configuration
while getopts :os in OPT
do
	case $OPT in
		o)
			TEMPLATE=$TEMPLATE_ONDEMAND
			;;
		s)
			TEMPLATE=$TEMPLATE_SPOT
			;;
		*)
			echo "Error: invalid option"
			usage
			exit 1
			;;
	esac
	echo $TEMPLATE
	shift
done

# Check for filename
if [[ $# != 1 ]]
then
	echo "Error: argument required"
	usage
	exit 1
else
	FILE=$1
fi

# Edit file
if [[ -f ${CONFDIR}/$FILE ]]
then
	echo "File Found: $FILE"
else
	cp ${CONFDIR}/spot ${CONFDIR}/$FILE
fi 	

echo $EDITOR ${CONFDIR}/$FILE
