#!/usr/bin/env bash

INSTANCE=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)

aws ec2 describe-instances --instance-id $INSTANCE --query "Reservations[*].Instances[*].PublicIpAddress" --output=text
