#!/bin/bash
#
# install packages
#
##

PKGDIR=/opt/pkgs
PKGS=(
git 
tmux 
)

# Install updates
#yum update -y

# Install packages
yum install -y ${PKGS[*]}

# Install EPEL
EPELDIR=/opt/pkgs/epel
mkdir -p $EPELDIR; cd $EPELDIR
curl -O https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm 2> /dev/null &&
yum localinstall -y epel-release-latest-7.noarch.rpm

# Install anaconda
ANACONDADIR=${PKGDIR}/anaconda
mkdir -p $ANACONDADIR; cd $ANACONDADIR
curl -O https://repo.continuum.io/archive/Anaconda3-5.0.0-Linux-x86_64.sh &&
bash Anaconda3-5.0.0-Linux-x86_64.sh -b -p ${ANACONDADIR}/3.6
