#!/bin/bash
#
# install packages
#
##

PKGDIR=/data/opt/pkgs
PKGS=(
epel-release
git 
openmpi
tmux 
)

# Install Updates
#yum update -y

# Install packages
yum install -y ${PKGS[*]}

### CUSTOM PACKAGES

# Install Anaconda
ANACONDADIR=${PKGDIR}/anaconda
if [[ ! -d $ANACONDADIR ]]
then
	mkdir -p $ANACONDADIR; cd $ANACONDADIR
	curl -O https://repo.continuum.io/archive/Anaconda3-5.0.0-Linux-x86_64.sh &&
	bash Anaconda3-5.0.0-Linux-x86_64.sh -b -p ${ANACONDADIR}/3.6 && 
	rm Anaconda3-5.0.0-Linux-x86_64.sh
fi

# Install Environment Modules
echo "/data/etc/modulefiles" >> /usr/share/Modules/init/.modulespath

# Install Intel Compilers
INTELDIR=${PKGDIR}/intel
if [[ ! -d $INTELDIR ]]
then
	mkdir -p $INTELDIR; cd $INTELDIR
	curl -O http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/12062/parallel_studio_xe_2018_professional_edition.tgz
fi
