#!/usr/bin/env bash

HOMEDIR=/data/home
USERS=(tonyvo asheph)

## Prep ubuntu user
usermod -d ${HOMEDIR}/ubuntu ubuntu

## Add users
for USERNAME in ${USERS[@]}
do
	useradd -d $HOMEDIR/$USERNAME $USERNAME
done
