#!/usr/bin/env bash

HOMEDIR=/data/home
USERS=(tonyvo asheph)

## Change home dir for centos
usermod -d ${HOMEDIR}/centos centos

## Add users
for USERNAME in ${USERS[@]}
do
	useradd -d $HOMEDIR/$USERNAME $USERNAME
done
