#!/bin/bash
#
# install packages
#
##

PKGDIR=/data/opt/pkgs
PKGS=(
   environment-modules
   expect
   git 
)

# Enable 32-bit packages
dpkg --add-architecture i386

# Install Updates
aptitude update
aptitude upgrade

# Install packages
apt-get install -y ${PKGS[@]}

### CUSTOM PACKAGES


# Install Anaconda
ANACONDADIR=${PKGDIR}/anaconda
if [[ ! -d $ANACONDADIR ]]
then
	mkdir -p $ANACONDADIR; cd $ANACONDADIR
	curl -O https://repo.continuum.io/archive/Anaconda3-5.0.0-Linux-x86_64.sh &&
	bash Anaconda3-5.0.0-Linux-x86_64.sh -b -p ${ANACONDADIR}/3.6 && 
	rm Anaconda3-5.0.0-Linux-x86_64.sh
fi

# Install Environment Modules
echo "/data/etc/modulefiles" >> /usr/share/modules/init/.modulespath

# Install Intel Compilers
INTELDIR=${PKGDIR}/intel
if [[ ! -d $INTELDIR ]]
then
        mkdir -p $INTELDIR; cd $INTELDIR
        curl -O http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/12062/parallel_studio_xe_2018_professional_edition.tgz
fi
 
# Configure SGE
source /etc/profile.d/sge.sh
cat <<+ >/tmp/all.q
qname                 all.q
hostlist              @allhosts
seq_no                0
load_thresholds       np_load_avg=1.75
suspend_thresholds    NONE
nsuspend              1
suspend_interval      00:05:00
priority              0
min_cpu_interval      00:05:00
processors            UNDEFINED
qtype                 BATCH INTERACTIVE
ckpt_list             NONE
pe_list               make smp mpi
rerun                 FALSE
slots                 1
tmpdir                /tmp
shell                 /bin/sh
prolog                NONE
epilog                NONE
shell_start_mode      unix_behavior
starter_method        NONE
suspend_method        NONE
resume_method         NONE
terminate_method      NONE
notify                00:00:60
owner_list            NONE
user_lists            NONE
xuser_lists           NONE
subordinate_list      NONE
complex_values        NONE
projects              NONE
xprojects             NONE
calendar              NONE
initial_state         default
s_rt                  INFINITY
h_rt                  INFINITY
s_cpu                 INFINITY
h_cpu                 INFINITY
s_fsize               INFINITY
h_fsize               INFINITY
s_data                INFINITY
h_data                INFINITY
s_stack               INFINITY
h_stack               INFINITY
s_core                INFINITY
h_core                INFINITY
s_rss                 INFINITY
h_rss                 INFINITY
s_vmem                INFINITY
h_vmem                INFINITY
+

cat <<+ >/tmp/autoscale.q
qname                 autoscale.q
hostlist              localhost
seq_no                0
load_thresholds       np_load_avg=1.75
suspend_thresholds    NONE
nsuspend              1
suspend_interval      00:05:00
priority              0
min_cpu_interval      00:05:00
processors            UNDEFINED
qtype                 BATCH INTERACTIVE
ckpt_list             NONE
pe_list               make smp mpi
rerun                 FALSE
slots                 0
tmpdir                /tmp
shell                 /bin/sh
prolog                NONE
epilog                NONE
shell_start_mode      unix_behavior
starter_method        NONE
suspend_method        NONE
resume_method         NONE
terminate_method      NONE
notify                00:00:60
owner_list            NONE
user_lists            NONE
xuser_lists           NONE
subordinate_list      NONE
complex_values        NONE
projects              NONE
xprojects             NONE
calendar              NONE
initial_state         default
s_rt                  INFINITY
h_rt                  INFINITY
s_cpu                 INFINITY
h_cpu                 INFINITY
s_fsize               INFINITY
h_fsize               INFINITY
s_data                INFINITY
h_data                INFINITY
s_stack               INFINITY
h_stack               INFINITY
s_core                INFINITY
h_core                INFINITY
s_rss                 INFINITY
h_rss                 INFINITY
s_vmem                INFINITY
h_vmem                INFINITY
+

qconf -Mq /tmp/all.q
qconf -Aq /tmp/autoscale.q
