#!/usr/bin/env bash

HOMEDIR=/data/home
USERS=(tonyvo asheph)

## Prep centos user
usermod -d ${HOMEDIR}/centos centos

## Add users
for USERNAME in ${USERS[@]}
do
	useradd -d $HOMEDIR/$USERNAME $USERNAME
done
